events {}

http {

    upstream movie_backend {
        server movie-app:8000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://movie_backend;
        }
    }
}